language: android
android:
  components:
    # Latest platform Tools
    - platform-tools

    # The BuildTools version used by your project
    - tools
    - build-tools-23.0.3

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

script:
    - ./gradlew build connectedCheck