language: android
android:
  components:

    # The BuildTools version used by your project
    - tools
	# update to latest, cannot control version
    - tools 

    # Latest platform Tools
    - platform-tools

    - build-tools-24.0.2

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

script:
    - ./gradlew build connectedCheck