# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    # Specify a working directory
    working_directory: ~/repo

    docker:
      # specify a container to build in, should match project API level
      - image: circleci/android:api-29

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:

      # Checkout the code
      - checkout

      # Download and restore dependency cache
      - restore_cache:
          keys:
            # Use both build.gradle files to get a specific cache
            - jars-{{ checksum "build.gradle" }}-{{ checksum "mobile/build.gradle" }}

      # Update our dependencies
      - run: ./gradlew androidDependencies

      # Save our gradle stuff, depenencies, gradle distribution
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "mobile/build.gradle" }}

      # Build the debug APK
      - run:
          name: Build debug APK
          command: ./gradlew :mobile:assembleDebug

      # Run tests. Note, not running :mobile:check
      - run:
          name: Run Tests
          command: ./gradlew :mobile:lint :mobile:test

      # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
      - store_artifacts:
          path: mobile/build/reports
          destination: reports

      # Store our APK so we can have nightly builds
      - store_artifacts:
          path: mobile/build/outputs/apk
          destination: apks

      # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      # Familiar currently doesn't generate this folder
      # - store_artifacts:
      #    path: mobile/build/test-results
